name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - devops-publish

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  Create_Docker_Image:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-angular-17:${{ github.event.repository.pushed_at }}

  Deploy_to_Cloudflare_Workers:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: Create_Docker_Image
    steps:
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./cloudflare-worker"
          command: publish
