name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - devops-publish

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-angular-17:${{ github.event.repository.pushed_at }}

      - name: Deploy to cluster
        uses: ThomasKliszowski/setup-kubectl@v1
        with:
          kube-config: ${{ secrets.KUBE_CONFIG_DATA }}
          kube-version: 1.15.0
      - run: kubectl set image --namespace ns-pokedex-angular-17 deployment/pokedex-angular-17 pokedex-angular-17=${{ secrets.DOCKER_HUB_USERNAME }}/pokedex-angular-17:${{ github.event.repository.pushed_at }}
